-- For each technology, check what it unlocks, and base the research cost on that
-- e.g. technology logistics unlocks recipes: 
-- Splitter: 5x green circuit + 5x iron plate + 4x yellow belt
-- Underground: 10x iron plate + 5x yellow belt
-- Total: 5x green circuit + 15x iron plate + 9x yellow belt
-- One research increment costs 1 automation science pack
-- The net cost for one increment is (sum of sciences per increment) * (sum of each recipe ingredient)
-- So the net cost (ingredients) for one technology research: (1 * 5) green circuit + (1 * 15) iron plate + (1 * 9) yellow belt
-- The rest of the technology unit remains the same; count, count_formula, time
-- Technology with a trigger unlock will not be affected